name: Create PR after Tests

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Criar Pull Request automaticamente
        uses: actions/github-script@v6
        with:
          script: |
            const branch = '${{ github.event.workflow_run.head_branch }}';
            const baseBranch = 'main';

            if (branch === baseBranch) {
              console.log(`Branch ${branch} é a base. Nada será feito.`);
              return;
            }

            const existingPRs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              base: baseBranch,
              state: 'open'
            });

            if (existingPRs.data.length > 0) {
              console.log(`PR existente: ${existingPRs.data[0].html_url}`);
              return;
            }

            try {
              const pr = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[Auto] ${branch} → ${baseBranch}`,
                head: branch,
                base: baseBranch,
                body: 'PR gerado automaticamente pelo GitHub Actions',
                draft: false
              });
              console.log(`PR criado: ${pr.data.html_url}`);
            } catch (error) {
              core.setFailed(`Erro ao criar PR: ${error.message}`);
            }
